import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/navBar";
import Section2 from "../components/section2";
import Hero from "../components/hero";
import Highlight from "../components/highlight";
import RoadMap from "../components/roadMapcop";
import Section3 from "../components/section3";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.body}>
      <Head>
        <title>Sol fennex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <NavBar />
        <Hero />
      </header>
      <main>
        <Section2 />
        <Section3 />
        <Highlight />
        <RoadMap />
        <br />
        <br />
        <br />
        <br />
      </main>

      <footer className={styles.footer}>footers</footer>
    </div>
  );
};

export default Home;
